TJ/urls.py
from django.conf.urls import url, include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^tjapp/', include('tjapp.urls', namespace='tjapp', app_name='tjapp')),
    url(r'^admin/', admin.site.urls),
]

tjapp/templates/tjapp/account/urls.py
import django
from django.conf.urls import url
from django.contrib.auth.views import login, logout, logout_then_login
from . import views
#from tjapp import views.logout

urlpatterns = [
    # url(r'^login/$', views.user_login, name='login'),
    url(r'^$', views.dashboard, name='dashboard'),

    url(r'^register/$', views.register, name='register'),
    url(r'^edit/$', views.edit, name='edit'),

    # login / logout urls
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.logoutUser, name='logout'),
    url(r'^logout-then-login/$', logout_then_login, name='logout_then_login'),

    # change password urls
    url(r'^password-change/$', django.contrib.auth.views.password_change, name='password_change'),
    url(r'^password-change/done/$', django.contrib.auth.views.password_change_done, name='password_change_done'),

    # restore password urls
    url(r'^password-reset/$', django.contrib.auth.views.password_reset, name='password_reset'),
    url(r'^password-reset/done/$', django.contrib.auth.views.password_reset_done, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', django.contrib.auth.views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^password-reset/complete/$', django.contrib.auth.views.password_reset_complete, name='password_reset_complete'),
]

tjapp/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    # url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.journeydefault, name='journeydefault'),
    url(r'^journeyadd', views.journeyadd, name='journeyadd'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),

 #   url(r'^login/$', views.lo, name='login')

  #  url(r'^logout/$', views.logout, { 'template_name': 'registration/logged_out.html',}, name='logout' ),

    url(r'^account/', include('tjapp.templates.tjapp.account.urls'))

    # url(r'post/new/$', views.post_new, name='post_new')
]

tjapp/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from TJ import settings


class Company(models.Model):
    Name = models.CharField(max_length=50)
    WebUrl = models.URLField(max_length=250, null=True)
    WebUrlContactUs = models.URLField(max_length=250, blank=True, default='')
    CustomerServicePhone = models.CharField(max_length=25, blank=True, default='')

    Created = models.DateTimeField(auto_now_add=True)
    Updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s' % (self.Name)


class Station(models.Model):
    DEFAULT_PK = 1
    Name = models.CharField(max_length=100)

    Created = models.DateTimeField(auto_now_add=True)
    Updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s' % (self.Name)


class Journey(models.Model):
    Company = models.ForeignKey(Company, related_name='company_journeys')
    User = models.ForeignKey(User, related_name='user_journey')
    DepartureStation = models.ForeignKey(Station, related_name='journey_station_dep', default=Station.DEFAULT_PK)
    ArrivalStation = models.ForeignKey(Station, related_name='journey_station_arr', default=Station.DEFAULT_PK)
    DelayAtDepartureStationMins = models.PositiveSmallIntegerField()
    IsCancelled = models.BooleanField()
    ScheduledDepartureTime = models.TimeField();
    ActualArrivalTime = models.TimeField(blank=True, null=True)
    Notes = models.CharField(max_length=250, blank=True, default='')
    IsVerified = models.BooleanField()

    Created = models.DateTimeField(auto_now_add=True)
    Updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Dep:%s Arr:%s DELAY: %d' % (
            self.DepartureStation.Name, self.ArrivalStation.Name, self.DelayAtDepartureStationMins)


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Profile(models.Model):
    user = models.OneToOneField(User)

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)




class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="draft")

    objects = models.Manager() # The default manager
    published = PublishedManager() # Our published manager - used in the post_list view

    def get_absolute_url(self):
        return reverse('tjapp:post_detail', args=[self.publish.year,
                                                  self.publish.strftime('%m'),
                                                  self.publish.strftime('%d'),
                                                  self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

# Create your models here.

tjapp/templates/tjapp/account/forms.py
from django import forms
from django.contrib.auth.models import User
from tjapp.models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        # From User fields
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        '''Check if both password matches'''
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

# class ProfileEditForm(forms.ModelForm):
#
#    class Meta:
#        model = Profile
#        fields = ('photo') # remove later

tjapp/templates/tjapp/forms.py
from django import forms
from django.shortcuts import render, redirect
from tjapp.models import models
from tjapp.models import Journey
from tjapp.models import User


class JourneyAddForm(forms.ModelForm):
    class Meta:
        model = Journey
        exclude = ('name', 'IsVerified', 'User')

tjapp/templates/tjapp/journey/forms.py
from django import forms
from tjapp.models import models
from tjapp.models import Journey
from tjapp.models import Company
from tjapp.models import User
from tjapp.models import Station


class JourneyAddForm(forms.ModelForm):
    class Meta:
        model = Journey
        exclude = ('name', 'IsVerified', 'User')

tjapp/templates/tjapp/post/forms.py
from django import forms
from tjapp.models import Post

class EmailPostForm(forms.Form):
    name=forms.CharField(max_length=25)
    email=forms.EmailField()
    to=forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

#
#class PostForm(forms.ModelForm):
#    class Meta:
#        model = Post
#        fields = ('title', 'body',)

tjapp/templates/tjapp/account/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import LoginForm, UserRegistrationForm, UserEditForm


def logoutUser(request):
   logout(request)
   #return HttpResponseRedirect('logged_out.html')
   return render(request, 'tjapp/account/logged_out.html', )


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/tjapp')
                    #return render(request, 'tjapp/journey/default.html')
                    #return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'tjapp/account/login.html', {'form': form})


@login_required
def dashboard(request):
    return render(request, 'tjapp/account/dashboard.html', {'section': 'dashboard'})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            # profile = Profile.objects.create(user=new_user)
            return render(request,
                          'tjapp/account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'tjapp/account/register.html', {'user_form': user_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        # profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid():  # and profile_form.is_valid():
            user_form.save()
            # profile_form.save()
            # messages.success(request, 'Profile updated successfully')
    else:
        # messages.success(request, 'Error updating your profile')
        user_form = UserEditForm(instance=request.user)
        # profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'tjapp/account/edit.html', {'user_form': user_form, })


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        #profile_form = ProfileEditForm(instance=request.user.profile,data=request.POST,files=request.FILES)
        if user_form.is_valid(): # and profile_form.is_valid():
            user_form.save()
            #profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        #profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'tjapp/account/edit.html', {'user_form': user_form,
                                                 # 'profile_form': profile_form
                  }
                  )

tjapp/views.py
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import RequestContext
from django.views.generic import ListView
from .models import Post
from tjapp.templates.tjapp.post.forms import EmailPostForm
from tjapp.templates.tjapp.forms import JourneyAddForm
from .models import Journey
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required


def journeydefault(request):
    return render(request, 'tjapp/default.html')


@login_required
def journeyadd(request):
    if request.method == 'POST':
        # Something
        journeyAddForm = JourneyAddForm(data=request.POST)
        if journeyAddForm.is_valid():
            # Create Journey object but don't save to the database yet
            new_journey = journeyAddForm.save(commit=False)

            new_journey.Model.User = request.user
            new_journey.save()

    else:
        form = JourneyAddForm()
    return render(request, 'tjapp/journeyadd.html', {'form': form})  # journey/


#def logout(request):
 #   return render(request, 'logged_out.html')


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form passed validation
            cd = form.cleaned_data  # dictionary of form fields and their values (VALID ones)
            # .... send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) wants to notify you that there is a delay at "{}"'.format(cd['name'], cd['email'],
                                                                                         post.title)
            message = 'Delay status at: "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'],
                                                                                 cd['comments'])
            send_mail(subject, message, 'martyraychev@gmail.com', [cd['to']])

            # Get the recipient email
            recipient = cd['to']
            sent = True
    else:
        form = EmailPostForm()
        recipient = False
        return render(request, 'tjapp/post/share.html',
                      {
                          'post': post,
                          'form': form,
                          'sent': sent,
                          'recipient': recipient}
                      )


# Create your views here.
def post_list(request):  # request required for all views
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)  # 3 post in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page not an INT - deliver Page 1
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'tjapp/post/list.html',
                  {'page': page, 'posts': posts})  # render the post with the given template


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'tjapp/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    return render(request, 'tjapp/post/detail.html', {'post': post})


def post_new(request):
    form = PostForm()
    return render(request, 'tjapp/post/post_edit.html', {'form': form})

tjapp/templates/tjapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <style type="text/css">
@import url(http://fonts.googleapis.com/css?family=Muli);

body {
    margin:0;
    padding:0;
    font-family:helvetica, sans-serif;
}

p {
    line-height: 1.8;
}

a {
    color:#12c064;
    text-decoration:none;
}

a:hover {
    color:#00a74f;
}

h1, h2, h3, h4, h5 , h6 { font-family: 'Muli', sans-serif; font-weight:normal; }

h1 {
    border-bottom:1px solid #bbb;
    padding:0 0 10px 0;
    margin:10px 0 20px 0;
}

h2 {
    margin:30px 0 20px;
}

ol {
    line-height:1.5;
}

#header {
    padding:10px 100px;
    font-size:14px;
    background:#12c064;
    color:#fff;
    border-bottom:4px solid #1cdf78;
    overflow:auto;
}

#header .logo {
    font-family: 'Muli', sans-serif;
    float:left;
    color:#f3f7cc;
    font-size:20px;
    margin-right:10%;
}

#header ul.menu {
    list-style:none;
    float:left;
    margin:0;
    padding:0;
}
#header ul.menu li {
    float:left;
    padding:4px 10px;
}

#header ul.menu li.selected a, #header ul.menu li.selected a:hover {
    color:#1b6d32;
    font-weight:bold;
}

#header a {
    color:#f3f7cc;
}
#header a:hover {
    color:#fff;
}

#header .user {
    float:right;
    padding-top:4px;
}

#content {
    padding:30px 100px;
}

/* forms */
form {
    overflow:auto;
}

form p {
    width:100%;
    overflow:auto;
}

label {
    float:left;
    clear:both;
    color:#333;
    margin-bottom:4px;
}
input, textarea {
    clear:both;
    float:left;
    margin:0 0 10px;
    background:#efefef;
    border:0;
    padding:6px 10px;
    font-size:14px;
}
input[type=submit], a.button {
    font-weight:bold;
    background:#12c064;
    color:#fff;
    padding:10px 20px;
    font-size:14px;
    text-transform:uppercase;
}
.errorlist {
    color:#cc0033;
    float:left;
    clear:both;
    padding-left:10px;
}
.helptext {
    margin:0 0 20px 0;
    color:#aaa;
    clear:both;
    float:left;
    font-size:13px;
}
/* messages */
ul.messages {
    margin:10px 100px;
    padding:0;
    list-style-type:
    none;
}
ul.messages li.success,
ul.messages li.warning,
ul.messages li.error,
ul.messages li.info {
    margin:0;
    padding:14px 20px;
    list-style:none;
    color:#fff;
}

ul.messages li.success { background:#81ce81; }
ul.messages li.success a { color:#0ac33e; }

ul.messages li.error { background:#a30029; color:#e9828e; }
ul.messages li.error a { color:#e9828e; }

ul.messages li.info { background:#faffae; color:#696b4e; }
ul.messages li.info a { color:#1586de; }

ul.messages li.warning { background:#de9404; }
ul.messages li.warning a { color:#f49000; }

ul.messages li a.close {
    margin:0;
    float:right;
    opacity:1;
    border:0;
    box-shadow:none;
    text-shadow:none;
}

.login-form {
    float:left;
}

/* social-auth */
.social {
    float:right;
}
.social li {
    list-style:none;
    padding:10px 20px;
    margin:0 0 10px 0;
}
.social li a {
    width:100%;
    height:100%;
    display:block;
    color:#fff;
}
.social li.facebook { background:#3b5399; }
.social li.twitter { background:#00cffa; }
.social li.google { background:#de1710; }


/* images */

.image-preview, .image-detail {
    max-width:300px;
    float:left;
    margin:0 20px 20px 0;
}
.image-detail { margin-top:20px; }
.image-info div {
    padding:20px 0;
    overflow:auto;
}
.count {
    color:#aaa;
    border:3px solid #bbb;
    border-radius:26px;
    padding:10px 20px;
    margin:20px 10px 0;
}
a.like, a.follow { float:right; margin-top:-8px; }

#image-list { overflow:auto; }
#image-list .image {
    float:left;
    width:220px;
    height:300px;
    margin:0 10px 10px 10px;
    border-top:8px solid #12c064;
    background:#eee;
}
#image-list img { width:220px; height:220px; }
#image-list .info { padding:10px; }
#image-list .info a { color:#333; }
.image-likes div {
    float:left;
    width:auto;
    padding:10px;
    text-align:center;
}
.image-likes img {
    width:120px;
    height:120px;
    border-radius:50%;
}

/* users */
#people-list img {
    width:180px;
    height:180px;
    border-radius:50%;
    margin-bottom:20px;
}
#people-list .user {
    width:180px;
    float:left;
    overflow:auto;
    padding:10px;
}
#people-list .info { text-align:center; }
img.user-detail {
    border-radius:50%;
    float:left;
}
.profile-info {
    float:left;
    overflow:auto;
    margin-right:20px;
}
.image-container { margin-top:40px; }

/* actions */
.action {
    clear:both;
    overflow:auto;
}
.action .images {
    float:left;
    margin:0 10px 10px 0;
}
.action .date {
    font-style:italic;
    color:#ccc;
}

    </style>
</head>
<body>
    <div id="header">
      <span class="logo">Bookmarks</span>
      {% if request.user.is_authenticated %}
      <ul class="menu">
          <li {% if section == 'dashboard' %} class='selected' {% endif %} >
             <a href="{% url 'tjapp:dashboard' %}">My dashboard</a>
          </li>
          <li {% if section == 'images' %} class='selected' {% endif %} >
             <a href="#">Images</a>
          </li>
          <li {% if section == 'people' %} class='selected' {% endif %} >
             <a href="#">People</a>
          </li>
      </ul>
      {% endif %}

      <span class="user">
        {% if request.user.is_authenticated %}
            Hello {{ request.user.first_name }},
            <a href="{% url 'tjapp:logout' %}">Logout</a>
        {% else %}
        <a href="{% url 'tjapp:login' %}">Log-in</a>  <a href="{% url 'tjapp:register' %}">Sign up</a>
        {% endif %}
      </span>
    </div>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }}">
            {{ message|safe }}
            <a href="#" class="close">✖</a>
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

tjapp/templates/tjapp/default.html
{% extends "tjapp/base.html" %}

{% block title  %}Welcome to Train Justice{% endblock %}
{% block content %}


  <h1>Welcome to Train Justice</h1>

  <a href="journeyadd.html">Add a Journey</a>

{% endblock %}

tjapp/templates/tjapp/journeyadd.html
{% extends 'tjapp/base.html' %}

{% block title %} Share a post {% endblock %}

{% block content %}
  {% if sent %}
     <h1>Journey delay successfully added</h1>
     <p>
         "{{ post.title }}" was successfully sent to {{recipient}}.
     </p>
  {% else %}
      <h1>Add a journey</h1>
      <form action="." method='post'>
        {{ form.as_p}}
        {% csrf_token %}

        <input type="submit" value="Add Journey"}/>
      </form>
  {% endif %}
{% endblock  %}

tjapp/templates/tjapp/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
           <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>